[.lead]
Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we'll get into the lab as soon as possible. That is where we will spend most of our time.

[.lead]
Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 2 hours.
* Participate. We are going to cut you loose in a live Ansible Tower instance here in just a little while. Have questions. Have opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!

[IMPORTANT]
.WiFi Access
====
ssid: `Red Hat Guest`

password: `atomic2016`
====

[.lead]
Today's Team

[.lead]
Tyler Cross - Ansible Solutions Architect

[.lead]
Jamie Duncan - Cloud Solutions Architect

Jamie has been at Red Hat for about 5 years and works with all things cloudy. He lives in Central Virginia on a soon-to-be farm when he's not on the road talking about OpenStack or Containers or Ansible or something else cloudy.

[.lead]
Bill Hirsch - Solutions Architect

Bill joined Red Hat earlier this year as an account architect focused on all things Red Hat. He joins us as a former customer where he specialized in Linux/Unix, automation, and monitoring. He lives in Pittsburgh with his wife, three boys, and too many pets.
